name: Flujo de trabajo reutilizable

on:
  workflow_call:
jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Paso 1
        run: echo "Este es el paso 1"
      - name: Paso 2
        run: echo "Este es el paso 2"
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: duvanquind/Calculator-java
      - name: listar
        run: |
          cd .
          tree
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
  reutilizar:
    uses: ./.github/workflows/workflow.yml
  matrix:
    uses: ./.github/workflows/matrix.yml
